### ISSUE TITLE
Payload verification error on Eve stable r79

### ISSUE THREAD

**Issue by Aerox912** [MuntashirAkon/chrome_os_updater#4]
Running the 2.0 release updater on my system resulted in a payload verification error after the download has finished.
My setup is Eve Version 79.0.3945.86 (Official Build) (64-bit), converted from FydeOS 8.1.

```
crosh> shell
 ~  export CUSTOM_RELEASE_TRACK=dev-channel                                                                                                          ✔  238  18:12:12 
 ~  sudo -E bash /usr/local/updater/chrome_os_updater/omaha_cros_update.sh                                                                           ✔  239  18:12:19 
Warning: using dev-channel, previous channel was stable-channel
Warning: Empty UUID for ROOT-A, default will be used.
Warning: Empty UUID for ROOT-B, default will be used.
Warning: Empty UUID for EFI-SYSTEM, default will be used.
Update available.
Downloading chromeos_12739.12.0_eve_dev-channel_full_mp-v2.bin-gvsgmyjqha2tfg3ky3pl5645ptsblhkk.signed (1.03 GB)...
################################################################################################################################################################### 100.0%
Verifying download...
Traceback (most recent call last):
  File "/usr/local/updater/chrome_os_updater/scripts/paycheck.py", line 29, in <module>
    from update_payload import common
  File "/usr/local/updater/chrome_os_updater/scripts/update_payload/__init__.py", line 20, in <module>
    from update_payload.checker import CHECKS_TO_DISABLE
  File "/usr/local/updater/chrome_os_updater/scripts/update_payload/checker.py", line 37, in <module>
    from update_payload import common
  File "/usr/local/updater/chrome_os_updater/scripts/update_payload/common.py", line 21, in <module>
    from update_payload import update_metadata_pb2
  File "/usr/local/updater/chrome_os_updater/scripts/update_payload/update_metadata_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/usr/local/updater/chrome_os_updater/scripts/google/protobuf/descriptor.py", line 38, in <module>
    import six
ImportError: No module named six
Download of https://dl.google.com/chromeos/eve/12739.12.0/dev-channel/chromeos_12739.12.0_eve_dev-channel_full_mp-v2.bin-gvsgmyjqha2tfg3ky3pl5645ptsblhkk.signed failed due to payload verification error.
```

**Comment by Aerox912** [comment]
After manually installing python six with chromebrew there is a new traceback

```
crosh> shell
 ~  export CUSTOM_RELEASE_TRACK=dev-channel                                                                                                          ✔  246  18:36:11 
 ~  sudo -E bash /usr/local/updater/chrome_os_updater/omaha_cros_update.sh                                                                           ✔  247  18:36:15 
Warning: using dev-channel, previous channel was stable-channel
Warning: Empty UUID for ROOT-A, default will be used.
Warning: Empty UUID for ROOT-B, default will be used.
Warning: Empty UUID for EFI-SYSTEM, default will be used.
Update available.
Downloading chromeos_12739.12.0_eve_dev-channel_full_mp-v2.bin-gvsgmyjqha2tfg3ky3pl5645ptsblhkk.signed (1.03 GB)...
################################################################################################################################################################### 100.0%
Verifying download...
Updating Chrome OS...
Traceback (most recent call last):
  File "/usr/local/updater/chrome_os_updater/scripts/paycheck.py", line 304, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/updater/chrome_os_updater/scripts/paycheck.py", line 274, in main
    payload.Apply(out_dst_parts, **dargs)
  File "/usr/local/updater/chrome_os_updater/scripts/update_payload/payload.py", line 332, in Apply
    helper.Run(new_parts, old_parts=old_parts)
  File "/usr/local/updater/chrome_os_updater/scripts/update_payload/applier.py", line 681, in Run
    new_part_info[name], old_parts.get(name, None), old_part_info[name])
  File "/usr/local/updater/chrome_os_updater/scripts/update_payload/applier.py", line 605, in _ApplyToPartition
    new_part_file, new_part_info.size)
  File "/usr/local/updater/chrome_os_updater/scripts/update_payload/applier.py", line 543, in _ApplyOperations
    self._ApplyReplaceOperation(op, op_name, data, new_part_file, part_size)
  File "/usr/local/updater/chrome_os_updater/scripts/update_payload/applier.py", line 266, in _ApplyReplaceOperation
    out_data = lzma.decompress(out_data)
NameError: global name 'lzma' is not defined
Failed to extract root image from update.
```

**Comment by MuntashirAkon** [comment]
Current workaround: (I'll  add it as an installer script later)

```bash
#!/bin/bash

# mount / as rw
mount -o rw,remount /

# Install crew
curl -Ls https://raw.github.com/skycocker/chromebrew/master/install.sh | bash
crew install setuptools

# Install python27
crew install python27

# Install pip
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python get-pip.py

# Install protobuf and lzma
pip install protobuf backports.lzma

# Delete backports
rm -rf /usr/local/updater/chrome_os_updater/scripts/backports
```

**Comment by MuntashirAkon** [comment]
Fixed via https://github.com/MuntashirAkon/chrome_os_updater/commit/ac3b380898a7081b27eadd839d9aeaf494bf5426
